In [2]:
import torch

In [3]:
# slope or weight
w = torch.tensor(2.0, requires_grad = True)

# Bias
b = torch.tensor(-1.0, requires_grad = True)

In [4]:
def forward(x):
    y = w*x + b
    return y

In [5]:
x = torch.tensor([1.0])

In [7]:
yhat = forward(x)

In [10]:
print(yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [15]:
x = torch.tensor([[1],[2]])

In [16]:
yhat_ = forward(x)

In [18]:
yhat_

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

## Linear Class

In [19]:
from torch.nn import Linear

In [20]:
torch.manual_seed(1)

In [53]:
# in_features is the size of each input sample or number of columns
# out features is the size of output sample

model = Linear(in_features = 1, out_features = 1)

In [54]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.4647]], requires_grad=True), Parameter containing:
tensor([0.9812], requires_grad=True)]


In [55]:
x = torch.tensor([0.0])

In [56]:
# y = wx+b

y  = model(x)

In [57]:
y

tensor([0.9812], grad_fn=<AddBackward0>)

In [70]:
model = Linear(in_features = 2, out_features = 1)

In [71]:
x = torch.tensor([[(1.0),(1.0)],[(2.0),(2.0)]])

In [72]:
yhat_ = model(x)

In [73]:
yhat_

tensor([[1.0992],
        [1.6317]], grad_fn=<AddmmBackward0>)

## Custom Module

In [75]:
import torch.nn as nn

In [79]:
class LR(nn.Module):
    def __init__(self, in_size, out_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_size, out_size)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [80]:
model = LR(1,1)

In [82]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0468]], requires_grad=True),
 Parameter containing:
 tensor([-0.6675], requires_grad=True)]

In [88]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[0.5153]])),
             ('linear.bias', tensor([-0.4414]))])

In [85]:
# to changes the weight and bias of the model

model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5153])
model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.4414])

In [86]:
x = torch.tensor([1.0])
yhat=model(x)

In [87]:
yhat

tensor([0.0739], grad_fn=<AddBackward0>)