In [6]:
from torch.utils.data import Dataset
import torch

## Dataset Object

In [32]:
class toy_data(Dataset):
    def __init__(self, length=100, transform = None):
        self.x = 2*torch.ones(length,2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

In [33]:
#dataset object is in list, touple or any python iterable 

dataset = toy_data()

In [34]:
print(dataset)

In [35]:
len(dataset)

100

In [36]:
dataset[2]

(tensor([2., 2.]), tensor([1.]))

In [37]:
for i in range(len(dataset)):
    x, y = dataset[i]
    print(i, "X: ", x, "Y: ", y)

0 X:  tensor([2., 2.]) Y:  tensor([1.])
1 X:  tensor([2., 2.]) Y:  tensor([1.])
2 X:  tensor([2., 2.]) Y:  tensor([1.])
3 X:  tensor([2., 2.]) Y:  tensor([1.])
4 X:  tensor([2., 2.]) Y:  tensor([1.])
5 X:  tensor([2., 2.]) Y:  tensor([1.])
6 X:  tensor([2., 2.]) Y:  tensor([1.])
7 X:  tensor([2., 2.]) Y:  tensor([1.])
8 X:  tensor([2., 2.]) Y:  tensor([1.])
9 X:  tensor([2., 2.]) Y:  tensor([1.])
10 X:  tensor([2., 2.]) Y:  tensor([1.])
11 X:  tensor([2., 2.]) Y:  tensor([1.])
12 X:  tensor([2., 2.]) Y:  tensor([1.])
13 X:  tensor([2., 2.]) Y:  tensor([1.])
14 X:  tensor([2., 2.]) Y:  tensor([1.])
15 X:  tensor([2., 2.]) Y:  tensor([1.])
16 X:  tensor([2., 2.]) Y:  tensor([1.])
17 X:  tensor([2., 2.]) Y:  tensor([1.])
18 X:  tensor([2., 2.]) Y:  tensor([1.])
19 X:  tensor([2., 2.]) Y:  tensor([1.])
20 X:  tensor([2., 2.]) Y:  tensor([1.])
21 X:  tensor([2., 2.]) Y:  tensor([1.])
22 X:  tensor([2., 2.]) Y:  tensor([1.])
23 X:  tensor([2., 2.]) Y:  tensor([1.])
24 X:  tensor([2., 2.]) Y:

## Transform

In [44]:
class add_mul(object):
    
    def __init__(self, addx = 10,muly = 20):
        self.addx = addx
        self.muly = muly
        
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x+self.addx
        y = y*self.muly
        
        sample = x, y
        
        return sample

In [52]:
# Transform by creating transform object
a_m = add_mul()
x_, y_ = a_m(dataset[10])

In [53]:
y_

tensor([20.])

In [58]:
# Automatically apply the method when we call the method

a_m = add_mul()
dataset_ = toy_data(transform = a_m)  #_to signify that the transform method is applied

In [59]:
dataset_[2]

(tensor([12., 12.]), tensor([20.]))

## Transform Compose

In [62]:
from torchvision import transforms

In [63]:
class mult(object):
    def __init__(self, mul = 100):
        self.mul = mul
        
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        
        x = x * self.mul
        y = y * self.mul
        
        sample = x, y
        
        return sample

In [65]:
data_transform = transforms.Compose([add_mul(), mult()])

In [66]:
x_, y_ = data_transform(dataset[0])

In [67]:
x_

tensor([1200., 1200.])

In [68]:
y_

tensor([2000.])

In [69]:
# other approach

data_set_Transformed = toy_data(transform = data_transform)

In [71]:
data_set_Transformed[19]

(tensor([1200., 1200.]), tensor([2000.]))