In [14]:
import torch

### Creating 2D tensor

In [15]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [16]:
A = torch.tensor(a)

In [17]:
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [18]:
A.ndimension() #returns the number of dimensions

2

In [19]:
A.shape #returns the shape of the tensor

torch.Size([3, 3])

In [20]:
A.size() #returns the shape of the tensor

torch.Size([3, 3])

In [21]:
A.numel() #returns the number of elements in the tensor

9

### Slicing

In [22]:
A[1][2] #returns the element at the 1st row and 2nd column

tensor(23)

In [25]:
A[0, 0:1] #returns the elements at the 0th row and 0th column

tensor([11])

In [26]:
A[0, 0:2] #returns the elements at the 0th row and 0th and 1st columns

tensor([11, 12])

In [27]:
A[1:3, 2] #returns the elements at the 1st and 2nd rows and 2nd column

tensor([23, 33])

### Basic 2D tensor operation

In [28]:
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[2, 1], [1, 2]])

In [30]:
z = x + y #element-wise addition
z

tensor([[3, 1],
        [1, 3]])

In [33]:
2*y #scalar multiplication

tensor([[4, 2],
        [2, 4]])

In [34]:
z = x * y #element-wise multiplication
z

tensor([[2, 0],
        [0, 2]])

In [35]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])

In [37]:
C = torch.mm(A, B) #matrix multiplication
C

tensor([[0, 2],
        [0, 2]])